<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="welcome-PC" failures="2" tests="12" name="com.TestNG_TDD.mytest" time="0.063" errors="0" timestamp="2021-03-25T11:32:40 IST" skipped="10">
  <testcase classname="com.TestNG_TDD.mytest" name="credentials" time="0.016">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="pwd" time="0.010">
    <skipped/>
  </testcase> <!-- pwd -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="credentials" time="0.001">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="pwd" time="0.001">
    <skipped/>
  </testcase> <!-- pwd -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="pwd" time="0.001">
    <skipped/>
  </testcase> <!-- pwd -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="credentials" time="0.002">
    <failure message="expected [Gaya3] but found [Jiya]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Gaya3] but found [Jiya]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.TestNG_TDD.mytest.credentials(mytest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="pwd" time="0.004">
    <skipped/>
  </testcase> <!-- pwd -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="credentials" time="0.000">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="credentials" time="0.003">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="credentials" time="0.002">
    <skipped/>
  </testcase> <!-- credentials -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="pwd" time="0.001">
    <failure message="expected [Gaya3143] but found [Jiya298]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Gaya3143] but found [Jiya298]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.TestNG_TDD.mytest.pwd(mytest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pwd -->
  <system-out/>
  <testcase classname="com.TestNG_TDD.mytest" name="pwd" time="0.022">
    <skipped/>
  </testcase> <!-- pwd -->
  <system-out/>
</testsuite> <!-- com.TestNG_TDD.mytest -->
